apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: my-app
    namespace: argocd
  spec:
    destination:
      namespace: default
      server: https://100.64.0.1:6443
    project: default
    source:
      path: charts/prometheus-blackbox-exporter
      repoURL: https://github.com/prometheus-community/helm-charts.git
kind: List
metadata: {}
